# Generated by Django 5.2.6 on 2025-09-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='air force', max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(default='shoes', max_length=255)),
                ('is_featured', models.BooleanField()),
                ('brand', models.CharField(default='nike', max_length=255)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
