# Generated by Django 5.2.6 on 2025-09-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('apparel', 'Apparel'), ('accessories', 'Accessories')], default='Shoes', max_length=255),
        ),
    ]
