# Generated by Django 5.2.6 on 2025-09-23 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bola'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bola',
        ),
    ]
