# Generated by Django 5.2.6 on 2025-09-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='id_product',
        ),
    ]
