# Generated by Django 5.2.6 on 2025-09-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_id_product_id_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_product',
            new_name='id',
        ),
    ]
